### ISSUE TITLE
Migrate mdx-to-csf?

### ISSUE THREAD

**Issue by timsully** [alexlibby/cobalt#1]
Do you plan on updating to make this work with Storybook 8? Would be extremely helpful!

**Comment by alexlibby** [comment]
Hi @timsully - thank you for your interest: it's great to see the library being used, even if it's only a first version!

I'm sorry I've not been monitoring issues of late - there is a good reason why though: I'm actually working on an updated version of this library as we speak :-) It's part of a bigger project to release a second edition of my book "Creating Web Components with Svelte".

There will be a lot of changes in it - many of them to improve on the components I originally included, but one of the biggest will be to completely revamp SB support to version 8. I will be working on it as part of the update, so it may take a bit of time - I hope this is OK? I will push up changes as soon as timescales allow - I'll post here when I have any news.

**Comment by timsully** [comment]
Awesome, thanks for the reply and I look forward to buying your book and learning more about web components!
